print("Part 1 ---------- UserInfo 1")
initial = input("Enter your initial here:-")
firstname = input("Enter your first name here:-")
secondname = input("Enter your second name here:-")
age = input("Enter your age number:-")
place = input("Enter your place where you live:-")
hobbies = input("Enter your hobbies here:-")

print("----------------------------------------------")

print("Part 2 ---------- UserInfo 2")

schoolname = input("Name your school where you studied:-")
tenthmark = input("How much mark did you scored at 10th?:-")
twelvethmark = input("How much mark did you scored at 12th?:-")
collegename = input("Name your college where you studied:-")
allyrsmark = input("How much mark did you scored at college in total?:-")
course = input("Did you study any courses in online? (Yes/No):-")
certify = input("Did you get any certification in any online course? (Yes/No/Not yet):-")
companyname = input("Enter your company name here (companyname/none):-")
print("----------------------------------------------")

print("Your full details")
print("Your initial is:", initial)
print("Your first name is:", firstname)
print("Your second name is:", secondname)
print("Your age number is:", age)
print("Your place is:", place)
print("Your hoobies is:", hobbies)
print("Your school name is:", schoolname)
mark = int(tenthmark)
print("Your 10th marks is:", tenthmark)
marks = int(twelvethmark)
print("Your 12th marks is:", twelvethmark)
print("Your college name is:", collegename)
collegemark = int(allyrsmark)
print("Certification:", certify)
print("Company name:",companyname)
